filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
  - type: log
    fields:
      document_type: nodeapp
    fields_under_root: true
    paths:
      - /var/log/nodeapp/*.log

processors:
  - add_cloud_metadata: ~
  - decode_json_fields:
      fields: ["message"]
      target: ""
      max_depth: 3
      overwrite_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:80"]
